stages:
    - build
    - test
    - deploy

build:
    image: maven:3.9.6-eclipse-temurin-17-alpine
    stage: build
    script: 
        - mvn clean compile package
        - test -f target/*.jar

test:
    stage: test
    image: maven:3.9.6-eclipse-temurin-17-alpine
    script: 
        - mvn test
    
deploy to s3:
    stage: deploy
    image: 
        name: amazon/aws-cli:2.15.38
        entrypoint: [""]
    script:
        - aws --version
        - echo "Hello S3" > test.txt
        - aws s3 cp test.txt arn:aws:s3:::johnelesho-test/test.txt