stages:
    - build
    - test

variables:
    build_file_name: build/laptop.txt

build a laptop:
    image: alpine
    stage: build
    artifacts:
       paths:
           - "build"
    script:
        - echo "This is my first gitlab job"
        - mkdir build
        - touch $build_file_name
        - echo "Mainboard" >> $build_file_name
        - cat build/computer.txt
        - echo "Keyboard" >> $build_file_name
        - cat build/computer.txt

test laptop:
    image: alpine
    stage: test
    script:
        - test -f $build_file_name
        - grep "Mainboard" $build_file_name
        - grep "Keyboard" $build_file_name