stages:
    - build
    - test

build a laptop:
    image: alpine
    stage: build
    artifacts:
       paths:
           - "build"
    script:
        - echo "This is my first gitlab job"
        - mkdir build
        - touch build/computer.txt
        - echo "Mainboard" >> build/computer.txt
        - cat build/computer.txt
        - echo "Keyboard" >> build/computer.txt
        - cat build/computer.txt

test laptop:
    image: alpine
    stage: test
    script:
        - test -f build/computer.txt
        - grep "Mainboard" build/computer.txt
        - grep "Keyboard" build/computer.txt