stages:
    - build
    - test
build:
    image: maven:3.9.6-eclipse-temurin-17-alpine
    stage: build
    script: 
        - mvn clean compile build

test:
    image: maven:3.9.6-eclipse-temurin-17-alpine
    script: 
        - mvn test
    
